version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: receipt-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"   # dev mode
      # - "80:80"     # prod mode (uncomment + comment dev line)
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app # Mount the project directory
      - /app/node_modules # A named volume to preserve node_modules
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: receipt-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

