"""init tables

Revision ID: 1f775341a97c
Revises: 243fe07c4eee
Create Date: 2025-10-17 13:27:42.644615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f775341a97c'
down_revision: Union[str, Sequence[str], None] = '243fe07c4eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('expenses', sa.Column('receipt_id', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('expenses', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.create_foreign_key(None, 'expenses', 'receipts', ['receipt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('expenses', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('expenses', 'created_at')
    op.drop_column('expenses', 'receipt_id')
    op.drop_table('receipts')
    # ### end Alembic commands ###
